export { default as withColor } from './withColor'
export { default as withSpacing } from './withSpacing'
export { default as withTypography } from './withTypography'
export { default as withResponsive } from './withResponsive'
export { default as withOther } from './withOther'
